services:
  postgres:
    image: postgres:16-alpine
    container_name: algofox-postgres
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: algofox
      POSTGRES_PASSWORD: algofox
      POSTGRES_DB: algofox
    volumes:
      - postgres_data:/var/lib/postgresql/data

  redis:
    image: redis:7-alpine
    container_name: algofox-redis
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data

volumes:
  postgres_data:
  redis_data:
