apiVersion: v1
kind: ConfigMap
metadata:
  name: judge0-config
  namespace: algofox
data:
  judge0.conf: |
    JUDGE0_TELEMETRY_ENABLE=false
    MAINTENANCE_MODE=false
    ENABLE_WAIT_RESULT=true
    ENABLE_CALLBACKS=true
    ENABLE_ADDITIONAL_FILES=true
    MAX_QUEUE_SIZE=1000
    USE_CGROUPS=true

    # Internal Redis/DB for Judge0
    REDIS_HOST=judge0-redis
    REDIS_PORT=6379
    POSTGRES_HOST=judge0-db
    POSTGRES_PORT=5432
    POSTGRES_DB=judge0
    POSTGRES_USER=judge0

    # Sandbox Limits
    CPU_TIME_LIMIT=5
    MEMORY_LIMIT=128000
    MAX_PROCESSES_AND_OR_THREADS=60
