apiVersion: apps/v1
kind: Deployment
metadata:
  name: judge0-db
  namespace: algofox
spec:
  replicas: 1
  selector:
    matchLabels:
      app: judge0-db
  template:
    metadata:
      labels:
        app: judge0-db
    spec:
      containers:
      - name: postgres
        image: postgres:13.0
        env:
        - name: POSTGRES_USER
          value: "judge0"
        - name: POSTGRES_DB
          value: "judge0"
        - name: POSTGRES_PASSWORD
          valueFrom:
            secretKeyRef:
              name: judge0-secrets
              key: POSTGRES_PASSWORD
        - name: PGDATA
          value: "/var/lib/postgresql/data/pgdata"
        ports:
        - containerPort: 5432
        volumeMounts:
        - name: judge0-db-data
          mountPath: /var/lib/postgresql/data/
      volumes:
      - name: judge0-db-data
        persistentVolumeClaim:
          claimName: judge0-db-pvc
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: judge0-db-pvc
  namespace: algofox
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 5Gi
---
apiVersion: v1
kind: Service
metadata:
  name: judge0-db
  namespace: algofox
spec:
  ports:
  - port: 5432
  selector:
    app: judge0-db
