apiVersion: apps/v1
kind: Deployment
metadata:
  name: judge0-server
  namespace: algofox
spec:
  replicas: 1
  selector:
    matchLabels:
      app: judge0-server
  template:
    metadata:
      labels:
        app: judge0-server
    spec:
      containers:
      - name: server
        image: judge0/judge0:1.13.1
        ports:
        - containerPort: 2358
        securityContext:
          privileged: true
        envFrom:
        - configMapRef:
            name: judge0-config
        - secretRef:
            name: judge0-secrets
        volumeMounts:
        - name: judge0-conf
          mountPath: /judge0.conf
          subPath: judge0.conf
      volumes:
      - name: judge0-conf
        configMap:
          name: judge0-config
---
apiVersion: v1
kind: Service
metadata:
  name: judge0-server
  namespace: algofox
spec:
  type: NodePort
  ports:
  - port: 2358
    nodePort: 32358
  selector:
    app: judge0-server
