apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: algofox
resources:
  - namespace.yaml
  - secrets.yaml
  - config.yaml
  - judge0-db.yaml
  - judge0-redis.yaml
  - judge0.yaml
  - judge0-worker.yaml
  - judge0-keda.yaml
