apiVersion: v1
kind: Secret
metadata:
  name: judge0-secrets
  namespace: algofox
type: Opaque
stringData:
  # Judge0 DB & Redis
  POSTGRES_PASSWORD: "judge0password"
  REDIS_PASSWORD: "judge0password"
