apiVersion: apps/v1
kind: Deployment
metadata:
  name: algofox-app
  namespace: algofox
spec:
  replicas: 1
  selector:
    matchLabels:
      app: algofox-app
  template:
    metadata:
      labels:
        app: algofox-app
    spec:
      containers:
      - name: app
        image: agentcat1/algofox:latest # Use your Docker Hub image
        imagePullPolicy: Always
        ports:
        - containerPort: 3000
        envFrom:
        - configMapRef:
            name: algofox-config
        - secretRef:
            name: algofox-secrets
        resources:
          requests:
            cpu: "250m"
            memory: "512Mi"
          limits:
            cpu: "1000m"
            memory: "1Gi"
---
apiVersion: v1
kind: Service
metadata:
  name: algofox-app
  namespace: algofox
spec:
  ports:
  - port: 80
    targetPort: 3000
  selector:
    app: algofox-app
