apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: algofox
resources:
  - namespace.yaml
  - secrets.yaml
  - config.yaml
  - postgres.yaml
  - redis.yaml
  - app.yaml
  - app-hpa.yaml
  - ingress.yaml
