apiVersion: v1
kind: Secret
metadata:
  name: algofox-secrets
  namespace: algofox
type: Opaque
stringData:
  # App Secrets
  BETTER_AUTH_SECRET: "zpN6vAuvJwJ79IkeWIOPlwUoA5M1F2HG"
  GOOGLE_CLIENT_SECRET: "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"
  MICROSOFT_CLIENT_SECRET: "YGv8Q~VtCKO~ZnLkGH5v2gf1UEonHwC0FpYT6be1"

  # Database & Redis Passwords
  POSTGRES_PASSWORD: "algofox"
  REDIS_PASSWORD: "" # No password for local/internal redis by default as per your env, but good practice to add one

  # Connection Strings (Internal K8s DNS)
  DATABASE_URL: "postgresql://algofox:algofox@postgres:5432/algofox"
  REDIS_URL: "redis://redis:6379"
